import Head from "next/head";
import Link from 'next/link';
import {
  AiFillLinkedin,
  AiFillGithub,
  AiOutlineMail, 
  AiFillPhone
} from "react-icons/ai";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import myself from "../public/myself.png";
import DeAnza from "../public/DeAnza.jpg";
import UW from "../public/UW.jpg";
import Image from "next/image";
import project1 from "../public/project1.jpg";
import project2 from "../public/project2.jpg"

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons text-xl">Portofolio</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="https://drive.google.com/file/d/1O-tXf5Tffar40XLRBK5gYzygTBtzA1Vg/view?usp=sharing"
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Glenn William
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              A software developer specializing in backend development.
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl text-justfy-center">
            A dedicated Electrical and Computer Engineering scholar with nearly one year of hands-on experience in developing, testing, and 
            maintenance of software solutions, as evidenced by a successful internship, active involvement in hackathons, coding competitions, 
            and programming societies.
            </p>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Proficient in the development of endpoint systems, with the capability to create robust APIs and web services. Skilled in designing and implementing efficient function algorithms while ensuring comprehensive testing using a variety of tools and programming languages.
            </p>
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">
              <a href="https://www.linkedin.com/in/glennwilliam/" target="_blank" rel="noopener noreferrer">
                <AiFillLinkedin />
              </a>
              <a href="https://github.com/GlennWilliam" target="_blank" rel="noopener noreferrer">
                <AiFillGithub />
              </a>
            </div>
            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={myself} layout="fill" objectFit="cover" />
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white ">Education</h3>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={DeAnza} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                De Anza College <br></br>
                Cupertino, California <br></br>
                2021-2023
              </h3>
              <p className="py-2">
                
              </p>
              <h4 className="py-4 text-red-600">Associate Degree in Science in Computer Science for Transfer</h4>
              <p className="text-gray-800 py-1">Cummulative GPA: 4.0; summa cumlaude</p>
              <h4 className="py-4 text-teal-600">Relevant Coursework</h4>
              <p className="text-gray-800 py-1">Programming Methodologies</p>
              <p className="text-gray-800 py-1">x86 Processor Assembly Language and Computer Architecture</p>
              <p className="text-gray-800 py-1">Data Abstraction and Structures</p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={UW} width={100} height={100} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                University of Washington <br></br>
                Seattle, Washington <br></br>
                Expected Graduation: June 2025
              </h3>
              <p className="py-2">
                
              </p>
              <h4 className="py-4 text-red-600">Bachelor of Science in Electrical and Computer Engineering (BSECE)</h4>
              <p className="text-gray-800 py-1">Cummulative GPA: 3.95</p>
              <h4 className="py-4 text-teal-600">Relevant Coursework</h4>
              <p className="text-gray-800 py-1">Progamming for Signal Processing</p>
              <p className="text-gray-800 py-1">Circuit Analysis</p>
              <p className="text-gray-800 py-1">Analysis and Modeling of Electronic and Photonic Device</p>
            </div>
          </div>
        </section>

        <section>
          <h3 className="text-3xl py-1 dark:text-white ">Personal Projects</h3>
          <div className="lg:flex gap-10 py-4">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={project1} width={350} height={200} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Employee Account Management <br></br>
                Language used: PHP, HTML, CSS, JavaScript, MySQL
              </h3>
              <p className="text-md py-2 leading-6 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-lg text-justify">
                Conceptualized and developed a comprehensive web-based Employee Account Management System using an extensive tech stack, 
                including PHP, HTML, CSS, JavaScript, and MySQL. The system aimed to streamline employee data management and enforce precise access control.
                <br></br>
                <br></br>
                Successfully implemented essential functionalities for user registration, editing, and deletion, ensuring the meticulous maintenance of 
                employee data. Additionally, introduced a robust role management system to allocate specific permissions and access rights to 
                registered users. Leveraged MySQL for secure data storage and retrieval, contributing to enhanced data integrity and reliability.
              </p>
              <div className="py-4">
                <Link href="https://github.com/GlennWilliam/Employee-Account-Management-.git" passHref>
                  <a target="_blank" rel="noopener noreferrer">
                    <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md">
                      View on GitHub
                    </button>
                  </a>
                </Link>
              </div>
            </div>

            {/* Personal Project Item 2 */}
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={project2} width={350} height={200} />
              <h3 className="text-lg font-medium pt-8 pb-2">
                RESTful API for User Account
                <br></br> 
                Language used: Java, MySQL, Maven, pom.xml
              </h3>
              <p className="text-md py-2 leading-6 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-lg">
              Designed and executed a RESTful API system for user account management, enabling seamless CRUD (Create, Read, Update, Delete)
              operations on user records through standard HTTP methods such as PUT, POST, DELETE, and GET. The API strictly adheres to 
              industry best practices, ensuring proper HTTP status codes and delivering JSON responses. 
              <br></br>
              <br></br>
              Employed MySQL queries to retrieve and manipulate data in the database. Implemented JSON and query parameter handling for flexible data interaction.
              <br></br>
              <br></br>
              <br></br>
              <br></br>
              <br></br>
              <br></br>

              </p>
              <div className="py-4">
                <Link href="https://github.com/GlennWilliam/RESTful-API-for-User-Account-.git" passHref>
                  <a target="_blank" rel="noopener noreferrer">
                    <button className="bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 border-none rounded-md">
                      View on GitHub
                    </button>
                  </a>
                </Link>
              </div>
            </div>
          </div>
        </section>

        <section>
          <h3 className="text-3xl py-1 dark:text-white">Contact Information</h3>
          <div className="text-center p-10 py-10">
            <div className="text-2xl py-2 dark:text-white md:text-3xl">
              <p>
                <AiOutlineMail className="inline-block text-4xl mr-2" />
                Email: glennwilliam1009@gmail.com
              </p>
              <p>
                <AiFillPhone className="inline-block text-4xl mr-2" />
                Phone: +6281213198988
              </p>
            </div>
          </div>
        </section>

      

        
       
      </main>
    </div>
  );
}
